### ISSUE TITLE
EUC Tool kit -Cloudwatch information tab not working 

### ISSUE THREAD

**Issue by muddakkagarisudhakar** [aws-samples/euc-toolkit#2]
EUC Tool kit -Cloudwatch information tab not working

**Comment by muddakkagarisudhakar** [comment]
![EUC Toolkit-CloudInf](https://github.com/aws-samples/euc-toolkit/assets/147094895/dfd2419a-0bdb-4172-acb4-2ce1387836ea)

**Comment by muddakkagarisudhakar** [comment]
if i click on Get User Experience information Tab from Workspace,

Cloud watch information keeps loading no result.

**Comment by muddakkagarisudhakar** [comment]
Anyone is available..?

**Comment by morgnza** [comment]
Hey there, thank you for exploring the EUC Toolkit! We have tested internally and have not reproduced your issues when the prerequisites are met. This leads us to believe this is a misconfiguration instead of a bug. For the CloudWatch functionality, you will need AWS.Tools.CloudTrail, AWS.Tools.CloudWatch, and AWS.Tools.CloudWatchLogs. You will also need permissions to these APIs so that the toolkit can populate the information. You can read more on this topic in the [Launch Blog](https://aws.amazon.com/blogs/desktop-and-application-streaming/euc-toolkit/). 

Note that this is a MIT-0 licensed example, so it is as-is code. This means there is no direct line of support from AWS and no committed SLA on issues. That said, as you use the toolkit, do let us know if you have further issues or feature requests. We will review all new features before our next release. Thank you again!
